#!/bin/sh
# shellcheck shell=dash

set -e

tsc -p tsconfig.edge.json

mv dist/edge-esm/edge.js dist/edge.mjs
mv dist/edge-esm/jq-api.js dist/jq-api.mjs
sed 's/"\.\/jq-api\.js"/".\/jq-api.mjs"/' dist/edge.mjs > dist/edge.mjs.tmp
mv dist/edge.mjs.tmp dist/edge.mjs
rm -rf dist/edge-esm
rm -f dist/edge.js
